########################################################################
###                                                                  ###
###                             LOGGING                              ###
###                                                                  ###
########################################################################

# Log level (debug info warn error fatal panic)
log_level = "info"

########################################################################
###                                                                  ###
###                               HTTP                               ###
###                                                                  ###
########################################################################

# Interface (127.0.0.1 for local, 0.0.0.0 for any, or specific)
http_intf = "0.0.0.0"
# Port to listen
http_port = 8080

########################################################################
###                                                                  ###
###                             DATABASE                             ###
###                                                                  ###
########################################################################

# Output file (where data are stored)
output_file = "output.json"

########################################################################
###                                                                  ###
###                              EMAIL                               ###
###                                                                  ###
########################################################################

# Do we send emails to admin?
mail_enabled = true

# if mail_enabled is set to “false”, no need to set the following values
mail_username = ""
mail_password = ""
mail_server = ""
mail_port = 25
mail_sender = ""
mail_dest = ""
